# Port du Gateway (point d'entr�e unique)
server.port=8080

# Nom du service
spring.application.name=api-gateway

# URL d'Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# D�couverte automatique des microservices via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routes manuelles vers les microservices
spring.cloud.gateway.routes[0].id=ms-tiers
spring.cloud.gateway.routes[0].uri=lb://MS-TIERS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/tiers/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/tiers/(?<segment>.*), /api/${segment}

spring.cloud.gateway.routes[1].id=tiers-logistique
spring.cloud.gateway.routes[1].uri=lb://TIERS-LOGISTIQUE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/ordres-transport,/api/ordres-transport/**

# CORS pour le front Angular local
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:4200,http://localhost:4201
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true